### ISSUE TITLE
The style of selected page in Experimental Pagination is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [OfficeDev/office-ui-fabric-react#10321]
### Environment Information

- **Package version(s)**: `@uifabric/experiments@7.10.0`
- **Browser and OS versions**: no related

#### Actual behavior:

![image](https://user-images.githubusercontent.com/7271329/64006895-c59b9300-cb45-11e9-85eb-33755c91ed8b.png)

The `Page 2` button shouldn't have the style of a clickable link while the `Page 1` should.

##### [CodeSandBox](https://codesandbox.io/embed/goofy-burnell-uewj7?fontsize=14)
![image](https://user-images.githubusercontent.com/7271329/64007647-1fe92380-cb47-11e9-96dd-2a75bbebdb70.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/7271329/64007002-f8458b80-cb45-11e9-9274-04a780869c38.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? 
Yes

For now I've hacked this Pagination by
```css
.ms-Pagination-container {
  button[aria-selected=false] {
    color: #0078d4 !important;
    text-decoration: underline;
  }

  button[aria-selected=true] {
    color: rgb(96, 94, 92) !important;
    text-decoration: none !important;
  }
}
```

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
