### ISSUE TITLE
Multi select <Dropdown/> doesn't select item when clicking outside of label

### ISSUE THREAD

**Issue by mshindal** [OfficeDev/office-ui-fabric-react#10669]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mshindal/pen/RwbzZXG

#### Actual behavior:

When using a `<Dropdown/>` that has multi select enabled, clicking outside of the option's label (the text) does not select the option. 

This .gif demonstrates the issue. First, I click outside of the label in a single select dropdown, which selects the option. Then, I click outside of the label in a multi select dropdown, and the option is not selected. 

![recording](https://user-images.githubusercontent.com/3990260/65918774-1c43f900-e3a0-11e9-897e-7ea75e8147eb.gif)

#### Expected behavior:

Clicking anywhere on the option in multi-select mode should select it, to be consistent with the single select behavior. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: N/A

**Comment by mshindal** [comment]
I was able to fix this with the following CSS, however I am unsure what the side effects could be:

```css
.ms-Dropdown-items > .ms-Checkbox.ms-Dropdown-item {
  padding-left: 0;
  padding-right: 0;
}

.ms-Dropdown-items > .ms-Checkbox.ms-Dropdown-item > .ms-Checkbox-label {
  width: 100%;
  height: 100%;
  margin-left: 8px;
  margin-right: 8px;
}
```
