### ISSUE TITLE
DetailsList's Cells

### ISSUE THREAD

**Issue by nnikka** [OfficeDev/office-ui-fabric-react#1440]
- __Package version(s)__: ^2.7.0
- __Browser and OS versions__: All

Requested priority: Blocking

#### Describe the issue:

We need to add borders between detailsList's cells.

#### Actual behavior:

Table cell's are not divided by borders

![ui3](https://cloud.githubusercontent.com/assets/23611964/24797416/3b739e20-1ba2-11e7-9944-f3a339b1612d.gif)

#### Expected behavior:

Table cell's should be divided by borders or it should be possible to override Table cells

**Comment by micahgodbolt** [comment]
http://codepen.io/dzearing/pen/ygrqwB

Yeah, current default look doesn't make it very obvious that you can resize.

**Comment by nnikka** [comment]
Can we somehow add borders between them ?

**Comment by aleksandrjPersonal** [comment]
Decision is to not fix. Borders are left off by design.

**Comment by dzearing** [comment]
It is possible, but not recommended, to tweak the styling to add cell borders. We want to add a DetailsGrid component, specifically for this scenario, which works more like the Excel grid.

But if you really needed to do this, you could;

add an right border:

```css
.ms-DetailsRow-cell:after {
  content: '';
  left/top/width/height: 0;
  border-right: 1px solid black;
}
```

Then a border-bottom on the whole row:
```css
.ms-DetailsRow:after {
  content: '';
  left/top/width/height: 0;
  border-bottom: 1px solid black;
}
```

Example: 
http://codepen.io/dzearing/pen/MmgBqd?editors=0110
