### ISSUE TITLE
TextField: Let style addonString

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#2227]
There's no way to apply a style to the `addonString` generated by `TextField`. My best workaround currently is this fragile rule:

```scss
.ms-TextField {
    .ms-TextField-wrapper {
        div {
            div {
                max-width: 80px;

                span {
                    overflow: hidden;
                    text-overflow: ellipsis;
                    white-space: nowrap;
                    line-height: 30px;
                }
            }
        }
    }
}
```
[Try it - CodePen](https://codepen.io/pablonete/pen/rwgGbR?editors=0110)

I'm ready to contribute, but I don't know what's the desired solution between these alternatives:
- Add CSS name like `ms-TextField-addon`
- Create prop in the TextField like `addonStyle`

If there's a better workaround that I'm missing, I'd appreciate any help.
