### ISSUE TITLE
Details:List set style on odd numbered rows

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#3408]
How do i change the background color for odd numbered rows in a detailslist.

**Comment by dzearing** [comment]
This css rule would work. It's not built in as it hasn't been part of the design language so far.

```css
.ms-List-cell:nth-child(even) .ms-DetailsRow {
  background: #EEE;
}
```
