### ISSUE TITLE
Dropdowns do not open list of items

### ISSUE THREAD

**Issue by twaddell** [OfficeDev/office-ui-fabric-react#611]
- Firefox 50.0 Windows 10
- Chrome 54.0.2840.99 Windows 10

When clicking on a Dropdown component the list of items does not display.
Keyboard up/down still functions correctly and allows scrolling through items.

This is also occurring on the [Dropdown example page](http://dev.office.com/fabric#/components/dropdown)

**Comment by biogenez** [comment]
same problem in IE & Edge

**Comment by dzearing** [comment]
This has been fixed in the latest build. The issue wasn't related to dropdown, but manifested from LayerHost not being positioned correctly at 0, 0 fixed, which was causing layered content to scroll the page up, which would in turn cause onDismiss to fire.

It's pretty simple to work around; you can either update to the latest build, or just add the style on your page:

```css
.ms-LayerHost-overlay {
  position: fixed;
  z-index: 1000000; /* layered content should overlay other content. */
}
```

The site will be patched next week.
